### PR TITLE
Sl more updates on key abilities

### PR DESCRIPTION
**Pull request by SweepyBoop**
- Hunter trap is 25 sec cooldown now (30 sec with baseline passive 5 sec reduction)
- DK blinding sleet should be in CC category
- Survival Instinct only has 1 charge (guardian still 2 charges but not many in arena)
- Mage mirror image is baseline not talent
- Rogue kidney shot is baseline for all specs
- Add Gladiator's Emblem (BM trinket), the most widely used trinket in high end arena
- Add category = cc for warlock howl of terror

### CODE REVIEW

**Comment by SweepyBoop** [comment]
More ability updates, the most notable one being hunter traps.
I just realized why I kept getting trapped when the hunter traps were still on cd..

**Comment by vendethiel** [comment]
what happened to cooldowns_warlock?

**Comment by SweepyBoop** [comment]
> what happened to cooldowns_warlock?

You need to click load diff to show since git thinks it's large diff..
The actual change is only one place: add category = cc for howl of terror

To be safe, I'll run a beyond compare for the original file and the one in my branch to make sure the change is actually just that one line and no accidental changes

**Comment by SweepyBoop** [comment]
image

Not sure why git is treating one line change as "large diff", but running a beyond compare looks good.

**Comment by vendethiel** [comment]
You might've changed the line endings. I'd rather not include that commit because it muddles the git history (and breaks merges, blames, etc).

**Comment by SweepyBoop** [comment]
> You might've changed the line endings. I'd rather not include that commit because it muddles the git history (and breaks merges, blames, etc).

Sure, let's drop the changes in the warlock file for this pull request.

**Comment by SweepyBoop** [comment]
Or I can recreate a clean PR to properly include the warlock file one line change.

**Comment by vendethiel** [comment]
You can drop the commit or I can do it by manually merging the branch

**Pull request closed without merging**
