### PR TITLE
Shadowlands cooldown updates

### PR DESCRIPTION
**Pull request by OperationXen**
I've updated some of the existing cooldowns for changes made in Shadowlands, and added a few of the more impactful covenant abilities which are a big deal in the current meta; Convoke, Mindgames, The Hunt, Resonating Arrow

### CODE REVIEW

**Comment by vendethiel** [comment]
Thanks! I’ll try to take a look tomorrow and implement some covenant support (so if you use either spell from your covenant, it detects the other one) later.

**Comment by OperationXen** [comment]
That sounds like a great feature, will need all of the new covenant abilities adding of course (rather than just the big ones). Are you planning on adding something to the cooldown definition objects like:

LCD_SPELL[XXXX]
{
  class = "DRUID",
  covenant = "NIGHTFAE",
  duration = 4
}

If so I can start plugging that data in

**Comment by vendethiel** [comment]
yes, that's exactly what's planned

**Comment by vendethiel** [comment]
Merging this for now. Thanks!

**Comment by vendethiel** [comment]
I just pushed c3024a5. If you could try it out and give me feedback, that'd be helpful :). Thanks!

**Comment by vendethiel** [comment]
@OperationXen  I just pushed c3024a586f2d264bddc982892de97c05aa47d2ed. If you could try it out and give me feedback, that'd be helpful :). Thanks!

**Comment by OperationXen** [comment]
@vendethiel Sure thing mate

**Pull request merged**
