### PR TITLE
More ability update (clean PR to include the warlock file change)

### PR DESCRIPTION
**Pull request by SweepyBoop**
In previous PR something looked weird for the warlock file, recreating a clean PR to properly include that change.

### CODE REVIEW

**Comment by SweepyBoop** [comment]
Recreated a clean PR, can you reject the old one and check this one instead?

**Comment by SweepyBoop** [comment]
Updates:

- DK: add cc category to blinding sleet
- Hunter: freezing trap is now baseline 25s cd
- Warlock: add cc category to howl of terror; deathbolt cooldown should be 45 sec
- Add BM trinket which is widely used in arenas

**Comment by vendethiel** [comment]
Sorry, haven’t played wow since I last tested your previous PR.
I need to get to this.

**Review by vendethiel — APPROVED** [review]

**Comment by vendethiel** [comment]
Thanks

**Pull request merged**
